export const data = [
    'sleep bear general captain neighbor cause ask thing special instead been soldier factory certainly children consonant come mountain youth ring exciting attack being include',
    'student leader describe lake slabs basket party loose same particles tall necessary because easily camp bicycle string shown pale island sunlight pay become primitive',
    'iron labor little watch allow modern express prevent his here principal art occasionally protection ten grandmother gas order shape stepped as cool toy would',
    'merely middle uncle whenever birthday thing at shoulder familiar income rocket usually got clock travel tiny doubt knife record wheel easily exist hunt late',
    'belt calm sum labor enemy indeed end boy buffalo blanket alphabet read behind riding room pine examine rhythm recognize sunlight ship danger signal scientist',
    'progress form purpose yet route pick visitor attached mathematics zero entire eat crop enter born only touch inch press basket care does have office',
    'no donkey discover around belong coach universe short land return effect physical thin passage distance environment congress captain person calm darkness sheep strip fog',
    'depend cost pole information tone earlier collect pencil tune lay properly log base avoid planning horse citizen labor above certain leaf obtain tail thus',
    'native package purple important journey burn excited widely fort knew term gasoline worker chance balance gray if strength then continued disappear highest kill itself',
    'hard short shore earth heat scientific use command leaving studying range along opportunity snake cookies one eye believed greater plastic could band himself average',
    'quite halfway beautiful vertical system habit instance are steady might shore ask salt fun cook nothing oxygen promised waste exactly shoot pink slip discussion',
    'ruler straight morning parent storm say mental use powerful equal importance feed twenty huge glad lying base third accept only they pencil pleasant shot',
    'pay other idea available possibly pressure those realize naturally travel brass famous shaking mountain quick easy long exchange largest yellow saved go our being',
    'why aware cannot island soft read saw jump failed teacher bigger duck paint hundred who hollow oldest silk sweet without rapidly breakfast student swim',
    'production fog cool spite rise case however think blue sale program effect farmer occur lonely special evidence speech useful none grandfather draw kitchen citizen',
    'shorter receive course blew chicken pair eaten pie die wore paragraph bigger stuck duck habit will breathing lovely doll in cowboy born gone count',
    'shall notice bear leather make time hundred rough balance frame entirely well ordinary fought recently scientific complete cut flies mysterious speed experiment lake owner',
    'come scene spite anyone mud present different lying my beyond follow forward meet want is strength straight blank find voice climate stick can accept',
    'separate open corn court thick were welcome pattern handle outer wet happily cool change fur hope wolf aid largest clock balloon brought in century',
    'own problem imagine brought dance swim farther floor solution studying below victory moment jet life trunk name matter loose occur around road many gold',
    'nearer magic gold below end ourselves unusual creature appropriate gray part pure cover design was wash soon far girl person twice range up steady',
    'soon planet tent alphabet prove three myself burst above nice leather bone memory pot pay condition action silence distance political special pupil command principle',
    'hunt minerals crack heat stuck rabbit class force week grown president said purple shop musical city equally enjoy mad caught material slightly depth quickly',
    'two unless limited condition rich meat cabin opportunity late blank star against member cry direct combination such border bare oldest excellent course central empty',

]